### ISSUE TITLE
Order Module

### ISSUE THREAD

**Issue by achhapolia10** [smoke-trees/earnest-meri-bachat-backend#27]
An Order Module is needed to be added. 
Structures:
orders:
{
  gift: boolean;
  refId: string;
  voucherIds: [strings];
  recieverEmail: string;
  buyer: mongoID;
  datePurchased: datetime;
  totalAmount: float;
  recieverMobile: string;
  status: string (enum: [ success, failure ];
  refundRequired: boolean;
  refunded: boolean;
  gyftr: [gyftrOrder];
  pine: [pineOrder];
}

gyftrOrder:
{
  brand: string,
  guid: string,
  quantity: integer,
  denomination: float
}
pineOrder:
{
  brand: string,
  sku: string,
  quanitiy: integer,
  denomination: float
}

Routes for following operations have to be made:
* Create an order
* Read an order from the refID
* Read all orders for a given buyer
* Read all orders with refundRequired true and refunded false
* Read all orders from a buyer with a failed status
* Read all orders from a buyer with success status
* Update the success status of the order
* Update the refund required flag
* Update the refunded flag

**Comment by mdhishaamakhtar** [comment]
What is the timeline for this?

**Comment by mdhishaamakhtar** [comment]
Its impossible to create all the routes with end to end unit testing and client stubs by today

**Comment by achhapolia10** [comment]
The hard deadline is tomorrow at 12pm. But I would prefer done by today. And I know it's impossible to create routes, tests and stubs by tonight so don't bother about client stub now try completing the routes and tests.

**Comment by mdhishaamakhtar** [comment]
Cool.
